### PR TITLE
Binary Search 

### PR DESCRIPTION
**Pull request by RRAJ644**
BinarySearch/BinarySearch.java

### CODE REVIEW

**Comment by thesmartdeveloperr** [comment]
you don't need to add all those files. just the .java and .md file is sufficient...
can you pls do another PR with only those files added @RRAJ644 ?

**Comment by RRAJ644** [comment]
Ok

**Comment by RRAJ644** [comment]
@thesmartdeveloperr  I have removed the extra files

**Review by thesmartdeveloperr — CHANGES_REQUESTED** [review]
Pls add a file in the BinarySearch folder called BinarySearch.md or Readme.md, and write a few lines about the algorithm in it. I will merge then... @RRAJ644

**Pull request closed without merging**
