### PR TITLE
Kruskal Algorithm

### PR DESCRIPTION
**Pull request by Vrushti24**

### CODE REVIEW

**Comment by Vrushti24** [comment]
ADDED ALGORITHM

**Comment by thesmartdeveloperr** [comment]
pls also add a file named KruskalsAlgorithm.md with some details about the algorithm. rest of the .C file looks good.
Pls add it @Vrushti24 , and make the PR.

**Comment by Vrushti24** [comment]
U can check now @thesmartdeveloperr

**Comment by Vrushti24** [comment]
After u merge PR will my points will be  automatically considered on website or do I have to fill the form or something? @thesmartdeveloperr

**Comment by thesmartdeveloperr** [comment]
okay looks good @Vrushti24 , i am merging it.
your PR will automatically be considered for hacktoberfest, no need to fill any form or anything.
Thanks for contributing.

**Pull request merged**
